### ISSUE TITLE
Planning on next V5 update!

### ISSUE THREAD

**Issue by Zadezter** [ImpladeDeveloped/Implactor#1]
We're planning to make some changes and adding a less stuffs,

**TO-DO**:
× __Custom Languages.__
× __Add configuration.__
× __Fix alot of bugs.__

You can help our project by forking, adding codes and create a pull requests to make more improvements to Implactor plugin. And this is authorized and permissions were given by plugin developers.

**Comment by Wolfkid200444** [comment]
👍👌
