### ISSUE TITLE
The Class MoveEntityPacket it's dont have in altay :(

### ISSUE THREAD

**Issue by HumYaiJang** [ImpladeDeveloped/Implactor#10]
Please fix this XD

**Comment by Zadezter** [comment]
.. -_- altay?

**Comment by Zadezter** [comment]
I know ```MoveEntityPacket``` does not exist after name changed but,
The user who made a Pull Request to me, has renamed it from ```MoveEntityAbsolutePacket```  to ```MoveEntityPacket``` in **BotListener.php** file.

And what do you said, Altay?
