### ISSUE TITLE
Update: vIR-1.7.3 | Bedrock Update 1.6.x

### ISSUE THREAD

**Issue by Zadezter** [ImpladeDeveloped/Implactor#15]
There are short features will added, I had enough with it right now.

## What's new?
• Added message, sent to player when sold head with empty hand.
• After joined, plugin notice message will only shown to staff members/operators and no longer be displayed for players.

## Fix | TO-DO
• Fix variable ```$death``` for despawn corpses on  ```PlayerDeathEvent```
• Fix the foreach() error on ```AntiCaps``` and ```AntiSwearing``` after previous PR made a changes to add to languages from ```[]``` to ```$plugin->getLang();```
• Fix to make more stability.

##
You can help us to improve the Implactor plugin by change, and make a PR.

**Comment by iZeaoGamer** [comment]
If these changes have already happened, then it would be a lot easier if you added this to the releases tab on github.
