### ISSUE TITLE
[FALSE] Facts about Zade, don't edit my message.

### ISSUE THREAD

**Issue by iZeaoGamer** [ImpladeDeveloped/Implactor#25]
Hi, so I have a little problem.
Whenever Zade can't put any more poggit builds to his repo, another of his alt's come on named: Leo.
Personally, this can be fixed by disallowing this user to have more than one account. Additionally, this user does not need more than one account. Which then bypasses the poggit system, where it blocks your builds, it then turns to be a mess, and can cause issues such as: Making an alt, or even going to one JUST because his main account can't make anymore poggit builds. How sad.
I believe the user: "Leo" account should be banned from poggit, or github its self to reduce many alts created whenever a user is running out of builds to past to, and causes issues not just for Zade, but for everyone else.
Something needs to be done about this, and the reason why I posted it specifically here, and no where else, is because Zade created poggit builds here. Zade, if you're reading this, just stop making a useless alt called "Leo". Pointless, and retarded in my opinion. No wonder why your project almost got taken down more than once, oof.
But eh, I'm not here to insult Zade, as it'd be too easy. But I am trying to help this community grow, and making alts is not the way to go, so before telling me to "Shut up" as your best insults, read, and then take this into consideration.
Thank you.
Signed off - iZeaoGamer

**Comment by Zadezter** [comment]
Why would you ask that to my friend who were inactive on Github? -_-

**Comment by Zadezter** [comment]
You have a multiple accounts too, damn mature.

**Comment by Zadezter** [comment]
http://github.com/TheFixerDevelopment
http://github.com/iZeaoGamer
http://github.com/ZPlayzMCPE

**Comment by LilGuyMC** [comment]
LMAO

**Comment by xXNiceYT** [comment]
Ayo Logang Paul dropped out xd

**Comment by Zadezter** [comment]
Oof.

**Comment by Zadezter** [comment]
Leo is my friend.

**Comment by iZeaoGamer** [comment]
Don't lie.

**Comment by xXNiceYT** [comment]
Who’s leo

**Comment by iZeaoGamer** [comment]
His alt.

**Comment by iZeaoGamer** [comment]
Anyways, issue closed as you will do what I say. And this classes as issue resolved.

**Comment by xXNiceYT** [comment]
Having alt isn’t bad

**Comment by Wolfkid200444** [comment]
:D

**Comment by Wolfkid200444** [comment]
i have 3 Alts

**Comment by EvilDonaldJTrump** [comment]
:)

**Comment by SadGuyComplete** [comment]
:))))

**Comment by Leomord** [comment]
@iZeaoGamer What the hell, kind of the facts to him about me? And really? "My account was his alt"?

**Comment by Leomord** [comment]
I little helped him for changing the commit and codes.

**Comment by Leomord** [comment]
And no, this issue is not even resolved until you stop disturbing Zade.

**Comment by Zadezter** [comment]
You're still studying? @Leomord?

**Comment by Leomord** [comment]
I cannot focus on studying for my exams because you were messaging me on Twitter.

**Comment by Leomord** [comment]
As I said, I've been rarely to check my Twitter when the time of study.

**Comment by Zadezter** [comment]
Okay, then.

**Comment by Zadezter** [comment]
How about that guy?

**Comment by Leomord** [comment]
Ugh, I don't know him.

**Comment by Leomord** [comment]
False facts.

**Comment by Leomord** [comment]
If he commenting about you and me again, please block him, lock this issue or whatever.

**Comment by Zadezter** [comment]
Okay and sorry for disturbing you.

**Comment by Leomord** [comment]
Okay.

**Comment by Leomord** [comment]
After exams, I will help you for codes again.

**Comment by Leomord** [comment]
Just don't message me at this moment.

**Comment by Zadezter** [comment]
:( sorry and continue your study.

**Comment by Leomord** [comment]
Thanks.

**Comment by Zadezter** [comment]
Np.

**Comment by iZeaoGamer** [comment]
Okay, so I do not have any alts. Also, stop changing the topic. This issue is suppose to be relating to Leo being Zade's alt, not exams.
Also, I'm not disturbing Zade. I'm just saying what you all need to hear.
So again, think before explaining your thoughts. We all know what happened.
Thing is - Leo and zade have the same grammar leveled skilled (Both are bad at grammar), so I would've known Leo was Zade's alt, if you think about it.
So use your brain, and think before commenting on a closed issue again.
Thank you, and issue closed to prevent arguments.

**Comment by Zadezter** [comment]
Don't you close the issue, James.

**Comment by Zadezter** [comment]
You've never changed for 3 years, and still bad boy actually.
