### ISSUE TITLE
Update: Implactor | vIR-1.7.2 [Future Core]

### ISSUE THREAD

**Issue by Zadezter** [ImpladeDeveloped/Implactor#7]
We will trying for our best to fix alot of errors and cleanup the codes. Also we will adding some code stuff for languages and more.

## TO-DO

-  **Fix all bugs.**

- **Fix language messages, null problem.**

- **Cleanup the codes.**

- **Add gamemodes, ping and forms messages and texts to language config. (Need @Wolfkid200444 to translate it to Espanish. And book pages isn't confirmed to add!)**

- **Remove Rainbow Armor codes from menu UI, and put it into the normal command.**

- **Making a bot menu, with adding a Spawn and clear a bot buttons.**

- **Add money killer to config.**

- **Create a clear all DeathHuman entities command, it useful to clear some standing corpses and prevent lagg!**

- **Transfer the help command to UI.**

- **Fix the messing up the codes.**

- **Make this plugin is better and auhorized.**

- **Fix all functions on Bot Human, tasks and listeners!**

- **Adding more swear, ads and caps words.**

- **Soccer entity will changed.**

##

There is alot of tasks could have to do right now. So for people who suggest a languages, don't suggest at this time.

**Comment by Wolfkid200444** [comment]
Until i get out of school

**Comment by Wolfkid200444** [comment]
I Will check it when i get out of school

**Comment by Zadezter** [comment]
## Removed Features
• Book of Implactor (/ibook) - It's now being useless.

## Changes
• All languages has reseted. Deleted Malay and Espanish files.
• Added Bot UI menu. (Easy To People To Spawn and Clear all Bot Humans.)
• Soccer ball entity changed from Slime to Magma Cube.
• Added more messages on English Language.
• Fixed Rainbow Armor menu and now has confirmation UI to disable.
• Added alot of configurations.
