### ISSUE TITLE
error in HealtTask

### ISSUE THREAD

**Issue by HGHD-Developer** [ImpladeDeveloped/Implactor#7]
realy helpful plugin! i think it can be better than essentialspe, but in last poggit build is an error with HealthTask, players get an hard lagg and mc crash. :(
please fix, and you get an star from me 😄 
here is the crash log:

14:42:41 CRITICAL > Could not save Config /data/plugins/Implactor/config.yml: file_put_contents(/data/plugins/Implactor/config.yml): failed to open stream: No such file or directory

14:42:41 CRITICAL > Event 'pocketmine\event\player\PlayerJoinEvent' konnte nicht zu 'Implactor vIR-1.2.1' weitergegeben werden: Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 160 in Implactor\MainIR

14:42:41 CRITICAL > TypeError: "Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 160" (EXCEPTION) in "Implactor_dev-68.phar/src/Implactor/tasks/HealthTask" at line 32

14:42:41 DEBUG > #0 Implactor_dev-68.phar/src/Implactor/MainIR(160): Implactor\tasks\HealthTask->__construct(Implactor\MainIR object, pocketmine\Player object)

14:42:41 DEBUG > #1 src/pocketmine/plugin/MethodEventExecutor(38): Implactor\MainIR->onPlayerJoin(pocketmine\event\player\PlayerJoinEvent object)

14:42:41 DEBUG > #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Implactor\MainIR object, pocketmine\event\player\PlayerJoinEvent object)

14:42:41 DEBUG > #3 src/pocketmine/plugin/PluginManager(723): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerJoinEvent object)

14:42:41 DEBUG > #4 src/pocketmine/Player(1061): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerJoinEvent object)

14:42:41 DEBUG > #5 src/pocketmine/Player(1009): pocketmine\Player->doFirstSpawn()

14:42:41 DEBUG > #6 src/pocketmine/level/Level(2528): pocketmine\Player->sendChunk(integer 14, integer 19, pocketmine\network\mcpe\protocol\BatchPacket object)

14:42:41 DEBUG > #7 src/pocketmine/level/Level(2573): pocketmine\level\Level->sendChunkFromCache(integer 14, integer 19)

14:42:41 DEBUG > #8 src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer 14, integer 19, pocketmine\network\mcpe\protocol\BatchPacket object)

14:42:41 DEBUG > #9 src/pocketmine/scheduler/AsyncPool(163): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)

14:42:41 DEBUG > #10 src/pocketmine/scheduler/ServerScheduler(348): pocketmine\scheduler\AsyncPool->collectTasks()

14:42:41 DEBUG > #11 src/pocketmine/Server(2572): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 2559)

14:42:41 DEBUG > #12 src/pocketmine/Server(2335): pocketmine\Server->tick()

14:42:41 DEBUG > #13 src/pocketmine/Server(2248): pocketmine\Server->tickProcessor()

14:42:41 DEBUG > #14 src/pocketmine/Server(1842): pocketmine\Server->start()

14:42:41 DEBUG > #15 src/pocketmine/PocketMine(287): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /data/, string /data/plugins/)

14:42:41 DEBUG > #16 /data/pocketmine.phar(1): require_once(string phar:///data/pocketmine.phar/src/pocketmine/PocketMine.php)

14:42:41 INFO > »ZT« HonorGamerHD hat den Server Betreten! Viel Spaß!

14:43:13 CRITICAL > Event 'pocketmine\event\entity\EntityDamageEvent' konnte nicht zu 'Implactor vIR-1.2.1' weitergegeben werden: Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 236 in Implactor\MainIR

14:43:13 CRITICAL > TypeError: "Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 236" (EXCEPTION) in "Implactor_dev-68.phar/src/Implactor/tasks/HealthTask" at line 32

14:43:13 DEBUG > #0 Implactor_dev-68.phar/src/Implactor/MainIR(236): Implactor\tasks\HealthTask->__construct(Implactor\MainIR object, pocketmine\Player object)

14:43:13 DEBUG > #1 src/pocketmine/plugin/MethodEventExecutor(38): Implactor\MainIR->onDamage(pocketmine\event\entity\EntityDamageEvent object)

14:43:13 DEBUG > #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Implactor\MainIR object, pocketmine\event\entity\EntityDamageEvent object)

14:43:13 DEBUG > #3 src/pocketmine/plugin/PluginManager(723): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\entity\EntityDamageEvent object)

14:43:13 DEBUG > #4 src/pocketmine/command/defaults/KillCommand(95): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\entity\EntityDamageEvent object)

14:43:13 DEBUG > #5 src/pocketmine/command/SimpleCommandMap(283): pocketmine\command\defaults\KillCommand->execute(pocketmine\Player object, string kill, array Array())

14:43:13 DEBUG > #6 src/pocketmine/Server(2087): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string kill)

14:43:13 DEBUG > #7 src/pocketmine/Player(3054): pocketmine\Server->dispatchCommand(pocketmine\Player object, string kill)

14:43:13 DEBUG > #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(234): pocketmine\Player->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

14:43:13 DEBUG > #9 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

14:43:13 DEBUG > #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

14:43:13 DEBUG > #11 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

14:43:13 DEBUG > #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

14:43:13 DEBUG > #13 src/pocketmine/Player(3134): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

14:43:13 DEBUG > #14 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

14:43:13 DEBUG > #15 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string [MY IP], raklib\protocol\EncapsulatedPacket object, integer 0)

14:43:13 DEBUG > #16 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()

14:43:13 DEBUG > #17 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()

14:43:13 DEBUG > #18 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)

14:43:13 DEBUG > #19 vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()

14:43:13 DEBUG > #20 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()

14:43:13 DEBUG > #21 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1527511393.4392)

14:43:13 DEBUG > #22 src/pocketmine/Server(2248): pocketmine\Server->tickProcessor()

14:43:13 DEBUG > #23 src/pocketmine/Server(1842): pocketmine\Server->start()

14:43:13 DEBUG > #24 src/pocketmine/PocketMine(287): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /data/, string /data/plugins/)

14:43:13 DEBUG > #25 /data/pocketmine.phar(1): require_once(string phar:///data/pocketmine.phar/src/pocketmine/PocketMine.php)

14:43:13 INFO > HonorGamerHD starb

14:43:14 CRITICAL > Event 'pocketmine\event\player\PlayerRespawnEvent' konnte nicht zu 'Implactor vIR-1.2.1' weitergegeben werden: Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 251 in Implactor\MainIR

14:43:14 CRITICAL > TypeError: "Argument 1 passed to Implactor\tasks\HealthTask::__construct() must be an instance of Implactor\tasks\Main, instance of Implactor\MainIR given, called in phar:///data/plugins/Implactor_dev-68.phar/src/Implactor/MainIR.php on line 251" (EXCEPTION) in "Implactor_dev-68.phar/src/Implactor/tasks/HealthTask" at line 32

14:43:14 DEBUG > #0 Implactor_dev-68.phar/src/Implactor/MainIR(251): Implactor\tasks\HealthTask->__construct(Implactor\MainIR object, pocketmine\Player object)

14:43:14 DEBUG > #1 src/pocketmine/plugin/MethodEventExecutor(38): Implactor\MainIR->onRespawn(pocketmine\event\player\PlayerRespawnEvent object)

14:43:14 DEBUG > #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Implactor\MainIR object, pocketmine\event\player\PlayerRespawnEvent object)

14:43:14 DEBUG > #3 src/pocketmine/plugin/PluginManager(723): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerRespawnEvent object)

14:43:14 DEBUG > #4 src/pocketmine/Player(3850): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerRespawnEvent object)

14:43:14 DEBUG > #5 src/pocketmine/Player(2788): pocketmine\Player->respawn()

14:43:14 DEBUG > #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(162): pocketmine\Player->handlePlayerAction(pocketmine\network\mcpe\protocol\PlayerActionPacket object)

14:43:14 DEBUG > #7 src/pocketmine/network/mcpe/protocol/PlayerActionPacket(88): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handlePlayerAction(pocketmine\network\mcpe\protocol\PlayerActionPacket object)

14:43:14 DEBUG > #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\PlayerActionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

14:43:14 DEBUG > #9 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)

14:43:14 DEBUG > #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

14:43:14 DEBUG > #11 src/pocketmine/Player(3134): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

14:43:14 DEBUG > #12 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

14:43:14 DEBUG > #13 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 93.217.218.228 53809, raklib\protocol\EncapsulatedPacket object, integer 0)

14:43:14 DEBUG > #14 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()

14:43:14 DEBUG > #15 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()

14:43:14 DEBUG > #16 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)

14:43:14 DEBUG > #17 vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()

14:43:14 DEBUG > #18 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()

14:43:14 DEBUG > #19 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1527511394.5392)

14:43:14 DEBUG > #20 src/pocketmine/Server(2248): pocketmine\Server->tickProcessor()

14:43:14 DEBUG > #21 src/pocketmine/Server(1842): pocketmine\Server->start()

14:43:14 DEBUG > #22 src/pocketmine/PocketMine(287): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /data/, string /data/plugins/)

14:43:14 DEBUG > #23 /data/pocketmine.phar(1): require_once(string phar:///data/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by Enfornix** [comment]
I have fixed it. Go try that plugin if there's some error or not..

**Comment by HGHD-Developer** [comment]
sry but the same error is there :/

**Comment by MrLukePotatoes** [comment]
It works fine for me.

**Comment by HGHD-Developer** [comment]
@MrLukePotatoes  do you use altay turanic?

**Comment by Zadezter** [comment]
I didn't use critical particle.

**Comment by Enfornix** [comment]
Sorry, I removed Health just now. :(
